package GUI;

import Classes.Pembeli;
import Databases.Database;
import Databases.Fonts.ExFont;
import Databases.KonfFont;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

public class Konfirmasi extends javax.swing.JFrame {

    public Konfirmasi(Pembeli pembeli) {
        this.pembeli = pembeli;
        this.totalHarga = 0;

        try {
            this.konf = new KonfFont();
            this.Xfont = new ExFont();
        } catch (IOException | FontFormatException ex) {
            Logger.getLogger(Konfirmasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();

        if (pembeli.getJumlahSmartphone() == 0) {
            buttonKonfirmasi.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        fillerPreHeader = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        labelTitle = new javax.swing.JLabel();
        fillerMidHeader = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelEmail = new javax.swing.JLabel();
        fillerMid2Header = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        labelLogout = new javax.swing.JLabel();
        fillerPosHeader = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        panelBody = new javax.swing.JPanel();
        scrollBackground = new javax.swing.JScrollPane();
        panelBackground = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        fillerPreFooter = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        labelTotal = new javax.swing.JLabel();
        fillerMidFooter1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buttonKembali = new javax.swing.JButton();
        fillerMidFooter2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        buttonKonfirmasi = new javax.swing.JButton();
        fillerPosFooter = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juragan Smartphone - Pembayaran");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelHeader.setBackground(new java.awt.Color(0, 200, 255));
        panelHeader.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelHeader.setMinimumSize(new java.awt.Dimension(800, 60));
        panelHeader.setPreferredSize(new java.awt.Dimension(800, 60));
        panelHeader.setLayout(new javax.swing.BoxLayout(panelHeader, javax.swing.BoxLayout.LINE_AXIS));
        panelHeader.add(fillerPreHeader);

        labelTitle.setFont(Xfont.getBrussels(25)
        );
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Pembayaran");
        panelHeader.add(labelTitle);
        panelHeader.add(fillerMidHeader);

        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelEmail.setText(pembeli.getNama());
        panelHeader.add(labelEmail);
        panelHeader.add(fillerMid2Header);

        labelLogout.setForeground(new java.awt.Color(255, 255, 255));
        labelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogout.setText("Log out");
        labelLogout.setMaximumSize(new java.awt.Dimension(50, 100));
        labelLogout.setMinimumSize(new java.awt.Dimension(50, 100));
        labelLogout.setPreferredSize(new java.awt.Dimension(50, 100));
        labelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLogoutMouseExited(evt);
            }
        });
        panelHeader.add(labelLogout);
        panelHeader.add(fillerPosHeader);

        getContentPane().add(panelHeader);

        panelBody.setLayout(new java.awt.BorderLayout());

        scrollBackground.setBorder(null);
        scrollBackground.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollBackground.setToolTipText("");
        scrollBackground.getVerticalScrollBar().setUnitIncrement(8);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new javax.swing.BoxLayout(panelBackground, javax.swing.BoxLayout.PAGE_AXIS));

        listSP();

        scrollBackground.setViewportView(panelBackground);

        panelBody.add(scrollBackground, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBody);

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));
        panelFooter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 200, 255)));
        panelFooter.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelFooter.setMinimumSize(new java.awt.Dimension(800, 60));
        panelFooter.setPreferredSize(new java.awt.Dimension(800, 60));
        panelFooter.setLayout(new javax.swing.BoxLayout(panelFooter, javax.swing.BoxLayout.LINE_AXIS));
        panelFooter.add(fillerPreFooter);

        labelTotal.setText("Total: Rp. " + String.format("%,d", totalHarga).replace(',', '.'));
        panelFooter.add(labelTotal);
        panelFooter.add(fillerMidFooter1);

        buttonKembali.setBackground(new java.awt.Color(0, 200, 255));
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("Kembali");
        buttonKembali.setMaximumSize(new java.awt.Dimension(105, 35));
        buttonKembali.setMinimumSize(new java.awt.Dimension(105, 35));
        buttonKembali.setPreferredSize(new java.awt.Dimension(105, 35));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        panelFooter.add(buttonKembali);
        panelFooter.add(fillerMidFooter2);

        buttonKonfirmasi.setBackground(new java.awt.Color(0, 200, 255));
        buttonKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        buttonKonfirmasi.setText("Konfirmasi");
        buttonKonfirmasi.setMaximumSize(new java.awt.Dimension(105, 35));
        buttonKonfirmasi.setMinimumSize(new java.awt.Dimension(105, 35));
        buttonKonfirmasi.setPreferredSize(new java.awt.Dimension(105, 35));
        buttonKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKonfirmasiActionPerformed(evt);
            }
        });
        panelFooter.add(buttonKonfirmasi);
        panelFooter.add(fillerPosFooter);

        getContentPane().add(panelFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        Home home = new Home(pembeli);
        home.setLocation(getLocation());
        home.setVisible(true);

        if (getExtendedState() == MAXIMIZED_BOTH) {
            home.setExtendedState(MAXIMIZED_BOTH);
        } else {
            home.setSize(getSize());
        }

        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void labelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelLogoutMouseClicked

    private void labelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseEntered
        labelLogout.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelLogoutMouseEntered

    private void labelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseExited
        labelLogout.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelLogoutMouseExited

    private void buttonKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKonfirmasiActionPerformed
        Pembayaran PB = new Pembayaran(pembeli);
        PB.setLocationRelativeTo(null);
        PB.setVisible(true);

        if (PB.getStatus() == true) {
            berhasilBayar();
        }
    }//GEN-LAST:event_buttonKonfirmasiActionPerformed

    private void berhasilBayar() {
        Database db = new Database();

        Date date = java.util.Calendar.getInstance().getTime();

        pembeli.getKeySmartphone().forEach(kode -> {
            try {
                db.recordPembelian(pembeli, kode, date.toString());
            } catch (IOException ex) {
                Logger.getLogger(Konfirmasi.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        int size = panelSP.length;

        for (int i = size - 1; i >= 0; i--) {
            pembeli.removeSmartphone(kodeSP[i]);
        }

        for (int i = 0; i < panelSP.length; i++) {
            panelSPHarga[i].remove(labelSPBuang[i]);
            labelSPHarga[i].setText("Sudah dibayar");

            panelSPHarga[i].revalidate();
            panelSPHarga[i].repaint();
        }

        labelTotal.setText(labelTotal.getText() + " (Lunas)");

        buttonKonfirmasi.setEnabled(false);
        buttonKonfirmasi.setText("Lunas");
    }

    private void listSP() {
        int i = 0;
        int size = pembeli.getJumlahSmartphone();

        panelSP = new javax.swing.JPanel[size];
        panelSPImg = new javax.swing.JPanel[size];
        panelSPDeskripsi = new javax.swing.JPanel[size];
        panelSPNama = new javax.swing.JPanel[size];
        panelSPHarga = new javax.swing.JPanel[size];
        labelSPImg = new javax.swing.JLabel[size];
        labelSPNama = new javax.swing.JLabel[size];
        labelSPRating = new javax.swing.JLabel[size];
        labelSPHarga = new javax.swing.JLabel[size];
        labelSPBuang = new javax.swing.JLabel[size];
        fillerSPPre = new javax.swing.Box.Filler[size];
        fillerSPMid = new javax.swing.Box.Filler[size];
        fillerSPPos = new javax.swing.Box.Filler[size];
        fillerSPNama = new javax.swing.Box.Filler[size];
        fillerSPHarga = new javax.swing.Box.Filler[size];
        separatorDeskripsi = new javax.swing.JSeparator[size];
        imageCover = new java.awt.Image[size];
        kodeSP = new String[size];

        for (String kode : pembeli.getKeySmartphone()) {
            try {
                imageCover[i] = ImageIO.read(new File("src/main/java/Databases/" + pembeli.getSmartphone(kode).getGambar()))
                        .getScaledInstance(100, 100, java.awt.Image.SCALE_AREA_AVERAGING);
            } catch (IOException ex) {
                Logger.getLogger(Konfirmasi.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }

        i = 0;

        for (String kode : pembeli.getKeySmartphone()) {
            panelSP[i] = new javax.swing.JPanel();
            fillerSPPre[i] = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
            panelSPImg[i] = new javax.swing.JPanel();
            labelSPImg[i] = new javax.swing.JLabel();
            fillerSPMid[i] = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
            panelSPDeskripsi[i] = new javax.swing.JPanel();
            panelSPNama[i] = new javax.swing.JPanel();
            labelSPNama[i] = new javax.swing.JLabel();
            fillerSPNama[i] = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
            labelSPRating[i] = new javax.swing.JLabel();
            separatorDeskripsi[i] = new javax.swing.JSeparator();
            panelSPHarga[i] = new javax.swing.JPanel();
            labelSPHarga[i] = new javax.swing.JLabel();
            fillerSPHarga[i] = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
            labelSPBuang[i] = new javax.swing.JLabel();
            fillerSPPos[i] = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

            panelSP[i].setBackground(new java.awt.Color(255, 255, 255));
            panelSP[i].setMaximumSize(new java.awt.Dimension(32767, 100));
            panelSP[i].setMinimumSize(new java.awt.Dimension(0, 100));
            panelSP[i].setPreferredSize(new java.awt.Dimension(800, 100));
            panelSP[i].setLayout(new javax.swing.BoxLayout(panelSP[i], javax.swing.BoxLayout.LINE_AXIS));
            panelSP[i].add(fillerSPPre[i]);

            panelSPImg[i].setMaximumSize(new java.awt.Dimension(100, 100));
            panelSPImg[i].setMinimumSize(new java.awt.Dimension(100, 100));
            panelSPImg[i].setPreferredSize(new java.awt.Dimension(100, 100));
            panelSPImg[i].setLayout(new java.awt.BorderLayout());

            labelSPImg[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelSPImg[i].setIcon(new javax.swing.ImageIcon(imageCover[i]));
            labelSPImg[i].setMaximumSize(new java.awt.Dimension(60, 90));
            labelSPImg[i].setMinimumSize(new java.awt.Dimension(60, 90));
            labelSPImg[i].setPreferredSize(new java.awt.Dimension(60, 90));
            panelSPImg[i].add(labelSPImg[i], java.awt.BorderLayout.CENTER);

            panelSP[i].add(panelSPImg[i]);
            panelSP[i].add(fillerSPMid[i]);

            panelSPDeskripsi[i].setLayout(new javax.swing.BoxLayout(panelSPDeskripsi[i], javax.swing.BoxLayout.PAGE_AXIS));

            panelSPNama[i].setBackground(new java.awt.Color(255, 255, 255));
            panelSPNama[i].setLayout(new javax.swing.BoxLayout(panelSPNama[i], javax.swing.BoxLayout.LINE_AXIS));

            labelSPNama[i].setText(pembeli.getSmartphone(kode).getNama() + " by " + pembeli.getSmartphone(kode).getMerek());
            labelSPNama[i].setMinimumSize(new java.awt.Dimension(0, 0));
            panelSPNama[i].add(labelSPNama[i]);
            panelSPNama[i].add(fillerSPNama[i]);

            labelSPRating[i].setFont(konf.getAwesome(18));
            labelSPRating[i].setForeground(new java.awt.Color(255, 255, 0));
            labelSPRating[i].setText(getStar(pembeli.getSmartphone(kode).getRating()));
            labelSPRating[i].setMaximumSize(new java.awt.Dimension(105, 25));
            labelSPRating[i].setMinimumSize(new java.awt.Dimension(105, 25));
            panelSPNama[i].add(labelSPRating[i]);

            panelSPDeskripsi[i].add(panelSPNama[i]);

            separatorDeskripsi[i].setForeground(new java.awt.Color(0, 0, 0));
            separatorDeskripsi[i].setMaximumSize(new java.awt.Dimension(32767, 2));
            separatorDeskripsi[i].setMinimumSize(new java.awt.Dimension(0, 2));
            panelSPDeskripsi[i].add(separatorDeskripsi[i]);

            panelSPHarga[i].setBackground(new java.awt.Color(255, 255, 255));
            panelSPHarga[i].setLayout(new javax.swing.BoxLayout(panelSPHarga[i], javax.swing.BoxLayout.LINE_AXIS));

            labelSPHarga[i].setText("Rp. " + String.format("%,d", (int) pembeli.getSmartphone(kode).getHarga()).replace(',', '.'));
            panelSPHarga[i].add(labelSPHarga[i]);
            panelSPHarga[i].add(fillerSPHarga[i]);

            labelSPBuang[i].setForeground(java.awt.Color.gray);
            labelSPBuang[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelSPBuang[i].setText("Batalkan");
            labelSPBuang[i].setMaximumSize(new java.awt.Dimension(50, 25));
            labelSPBuang[i].setMinimumSize(new java.awt.Dimension(50, 25));

            labelSPBuang[i].setName("" + i);

            labelSPBuang[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    labelBukuBuangMouseEntered(evt);
                }
            });

            labelSPBuang[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    labelBukuBuangMouseExited(evt);
                }
            });

            labelSPBuang[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    labelBukuBuangMouseClicked(evt);
                }
            });

            panelSPHarga[i].add(labelSPBuang[i]);

            panelSPDeskripsi[i].add(panelSPHarga[i]);

            panelSP[i].add(panelSPDeskripsi[i]);
            panelSP[i].add(fillerSPPos[i]);

            panelBackground.add(panelSP[i]);

            kodeSP[i] = kode;
            totalHarga += pembeli.getSmartphone(kode).getHarga();
            i++;
        }

    }

    private void labelBukuBuangMouseEntered(java.awt.event.MouseEvent evt) {
        javax.swing.JLabel label = (javax.swing.JLabel) evt.getSource();
        int num = Integer.parseInt(label.getName());

        labelSPBuang[num].setForeground(java.awt.Color.black);
    }

    private void labelBukuBuangMouseExited(java.awt.event.MouseEvent evt) {
        javax.swing.JLabel label = (javax.swing.JLabel) evt.getSource();
        int num = Integer.parseInt(label.getName());

        labelSPBuang[num].setForeground(java.awt.Color.gray);
    }

    private void labelBukuBuangMouseClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JLabel label = (javax.swing.JLabel) evt.getSource();
        int num = Integer.parseInt(label.getName());

        panelBackground.remove(panelSP[num]);

        panelBackground.revalidate();
        panelBackground.repaint();

        totalHarga -= pembeli.getSmartphone(kodeSP[num]).getHarga();

        labelTotal.setText("Total: Rp. " + String.format("%,d", totalHarga).replace(',', '.'));

        pembeli.removeSmartphone(kodeSP[num]);

        if (pembeli.getJumlahSmartphone() == 0) {
            buttonKonfirmasi.setEnabled(false);
        }
    }

    private String getStar(double rating) {
        String stars = "";

        for (int i = 0; i < (int) rating; i++) {
            stars += "\uf005";
        }

        if (rating - (int) rating == 0.5) {
            stars += "\uf089";
        }

        return stars;
    }

    private Pembeli pembeli;
    private int totalHarga;
    private KonfFont konf;
    private ExFont Xfont;

    // Varibles for Listed product
    private javax.swing.JPanel[] panelSP;
    private javax.swing.JPanel[] panelSPImg;
    private javax.swing.JPanel[] panelSPDeskripsi;
    private javax.swing.JPanel[] panelSPNama;
    private javax.swing.JPanel[] panelSPHarga;
    private javax.swing.JLabel[] labelSPImg;
    private javax.swing.JLabel[] labelSPNama;
    private javax.swing.JLabel[] labelSPRating;
    private javax.swing.JLabel[] labelSPHarga;
    private javax.swing.JLabel[] labelSPBuang;
    private javax.swing.JSeparator[] separatorDeskripsi;
    private javax.swing.Box.Filler[] fillerSPPre;
    private javax.swing.Box.Filler[] fillerSPMid;
    private javax.swing.Box.Filler[] fillerSPPos;
    private javax.swing.Box.Filler[] fillerSPNama;
    private javax.swing.Box.Filler[] fillerSPHarga;
    private java.awt.Image[] imageCover;
    private String[] kodeSP;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonKonfirmasi;
    private javax.swing.Box.Filler fillerMid2Header;
    private javax.swing.Box.Filler fillerMidFooter1;
    private javax.swing.Box.Filler fillerMidFooter2;
    private javax.swing.Box.Filler fillerMidHeader;
    private javax.swing.Box.Filler fillerPosFooter;
    private javax.swing.Box.Filler fillerPosHeader;
    private javax.swing.Box.Filler fillerPreFooter;
    private javax.swing.Box.Filler fillerPreHeader;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLogout;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane scrollBackground;
    // End of variables declaration//GEN-END:variables
}
