package GUI;

import Classes.Smartphone;
import Classes.Pembeli;
import Databases.KonfFont;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class PreviewSmartphone extends javax.swing.JDialog {

    public PreviewSmartphone(java.awt.Frame parent, Smartphone sp, Pembeli pembeli) {
        this.parent = parent;
        this.sp = sp;
        this.pembeli = pembeli;

        try {
            this.konf = new KonfFont();
            this.cover = ImageIO.read(new File("src/main/java/Databases/" + sp.getGambar()))
                    .getScaledInstance(100, 100, Image.SCALE_AREA_AVERAGING);
        } catch (IOException | FontFormatException e) {
            Logger.getLogger(PreviewSmartphone.class.getName()).log(Level.SEVERE, null, e);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLS = new javax.swing.JPanel();
        panelLSBody1 = new javax.swing.JPanel();
        panelLSCover = new javax.swing.JPanel();
        panelLSCoverSupport = new javax.swing.JPanel();
        labelLBCover = new javax.swing.JLabel();
        panelLSRating = new javax.swing.JLabel();
        panelLSNama = new javax.swing.JLabel();
        panelLSMerek = new javax.swing.JLabel();
        panelLBHarga = new javax.swing.JLabel();
        panelLSBody2 = new javax.swing.JPanel();
        scrollPaneLS = new javax.swing.JScrollPane();
        textAreaLSReview = new javax.swing.JTextArea();
        panelLSFooter = new javax.swing.JPanel();
        buttonLSKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        panelLS.setBackground(new java.awt.Color(255, 255, 255));
        panelLS.setMaximumSize(new java.awt.Dimension(600, 450));
        panelLS.setMinimumSize(new java.awt.Dimension(600, 450));
        panelLS.setLayout(new javax.swing.BoxLayout(panelLS, javax.swing.BoxLayout.PAGE_AXIS));

        panelLSBody1.setBackground(new java.awt.Color(255, 255, 255));
        panelLSBody1.setMaximumSize(new java.awt.Dimension(600, 225));
        panelLSBody1.setMinimumSize(new java.awt.Dimension(600, 225));
        panelLSBody1.setPreferredSize(new java.awt.Dimension(600, 225));
        java.awt.GridBagLayout panelLBBody1Layout = new java.awt.GridBagLayout();
        panelLBBody1Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0};
        panelLBBody1Layout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0};
        panelLSBody1.setLayout(panelLBBody1Layout);

        panelLSCover.setMaximumSize(new java.awt.Dimension(120, 180));
        panelLSCover.setMinimumSize(new java.awt.Dimension(120, 180));
        panelLSCover.setPreferredSize(new java.awt.Dimension(120, 180));

        panelLSCoverSupport.setMaximumSize(new java.awt.Dimension(120, 180));
        panelLSCoverSupport.setMinimumSize(new java.awt.Dimension(120, 180));
        panelLSCoverSupport.setLayout(new java.awt.BorderLayout());

        labelLBCover.setBackground(new java.awt.Color(255, 255, 255));
        labelLBCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLBCover.setIcon(new ImageIcon(cover));
        labelLBCover.setMaximumSize(new java.awt.Dimension(120, 180));
        labelLBCover.setMinimumSize(new java.awt.Dimension(120, 180));
        labelLBCover.setPreferredSize(new java.awt.Dimension(120, 180));
        panelLSCoverSupport.add(labelLBCover, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelLSCoverLayout = new javax.swing.GroupLayout(panelLSCover);
        panelLSCover.setLayout(panelLSCoverLayout);
        panelLSCoverLayout.setHorizontalGroup(
            panelLSCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLSCoverSupport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLSCoverLayout.setVerticalGroup(
            panelLSCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLSCoverSupport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        panelLSBody1.add(panelLSCover, gridBagConstraints);

        panelLSRating.setForeground(new java.awt.Color(255, 255, 0));
        panelLSRating.setFont(konf.getAwesome(18));
        panelLSRating.setText(getStar(sp.getRating()));
        panelLSRating.setPreferredSize(new java.awt.Dimension(400, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelLSBody1.add(panelLSRating, gridBagConstraints);

        panelLSNama.setText(String.format("<html><div WIDTH=%d>%s</div></html>", 400, sp.getNama()));
        panelLSNama.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelLSNama.setMaximumSize(new java.awt.Dimension(400, 90));
        panelLSNama.setMinimumSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelLSBody1.add(panelLSNama, gridBagConstraints);

        panelLSMerek.setText("<html>" + sp.getMerek() + "</html>");
        panelLSMerek.setPreferredSize(new java.awt.Dimension(400, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelLSBody1.add(panelLSMerek, gridBagConstraints);

        panelLBHarga.setText("Rp. " + sp.getHarga());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        panelLSBody1.add(panelLBHarga, gridBagConstraints);

        panelLS.add(panelLSBody1);

        panelLSBody2.setBackground(new java.awt.Color(255, 255, 255));
        panelLSBody2.setLayout(new java.awt.GridBagLayout());

        scrollPaneLS.setBorder(null);
        scrollPaneLS.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneLS.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPaneLS.setMaximumSize(new java.awt.Dimension(550, 150));
        scrollPaneLS.setMinimumSize(new java.awt.Dimension(550, 120));
        scrollPaneLS.setPreferredSize(new java.awt.Dimension(550, 150));

        textAreaLSReview.setEditable(false);
        textAreaLSReview.setBackground(new java.awt.Color(255, 255, 255));
        textAreaLSReview.setColumns(20);
        textAreaLSReview.setText("No Review");
        textAreaLSReview.setWrapStyleWord(true);
        textAreaLSReview.setBorder(null);
        scrollPaneLS.setViewportView(textAreaLSReview);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        panelLSBody2.add(scrollPaneLS, gridBagConstraints);

        panelLS.add(panelLSBody2);

        panelLSFooter.setBackground(new java.awt.Color(255, 255, 255));
        panelLSFooter.setMaximumSize(new java.awt.Dimension(600, 75));
        panelLSFooter.setMinimumSize(new java.awt.Dimension(600, 75));

        buttonLSKembali.setBackground(new java.awt.Color(212, 163, 115));
        buttonLSKembali.setText("Kembali");
        buttonLSKembali.setMaximumSize(new java.awt.Dimension(175, 50));
        buttonLSKembali.setMinimumSize(new java.awt.Dimension(175, 50));
        buttonLSKembali.setPreferredSize(new java.awt.Dimension(175, 50));
        buttonLSKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLSKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLSFooterLayout = new javax.swing.GroupLayout(panelLSFooter);
        panelLSFooter.setLayout(panelLSFooterLayout);
        panelLSFooterLayout.setHorizontalGroup(
            panelLSFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLSFooterLayout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(buttonLSKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelLSFooterLayout.setVerticalGroup(
            panelLSFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLSFooterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(buttonLSKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        panelLS.add(panelLSFooter);

        getContentPane().add(panelLS, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLSKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLSKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_buttonLSKembaliActionPerformed

    private String getStar(double rating) {
        String stars = "";

        for (int i = 0; i < (int) rating; i++) {
            stars += "\uf005";
        }

        if (rating - (int) rating == 0.5) {
            stars += "\uf089";
        }

        return stars;
    }
    
    public void beli(){
        pembeli.addSmartphone(sp.getKode(), sp);
    }

    private final Smartphone sp;
    private final Pembeli pembeli;
    private final java.awt.Frame parent;
    private KonfFont konf;
    private Image cover;
    //private Konfigurasi konfigurasi;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLSKembali;
    private javax.swing.JLabel labelLBCover;
    private javax.swing.JLabel panelLBHarga;
    private javax.swing.JPanel panelLS;
    private javax.swing.JPanel panelLSBody1;
    private javax.swing.JPanel panelLSBody2;
    private javax.swing.JPanel panelLSCover;
    private javax.swing.JPanel panelLSCoverSupport;
    private javax.swing.JPanel panelLSFooter;
    private javax.swing.JLabel panelLSMerek;
    private javax.swing.JLabel panelLSNama;
    private javax.swing.JLabel panelLSRating;
    private javax.swing.JScrollPane scrollPaneLS;
    private javax.swing.JTextArea textAreaLSReview;
    // End of variables declaration//GEN-END:variables
}
